export type Language = 'vi' | 'en';

export const portfolioContent = {
  vi: {
    nav: { about: 'VỀ TÔI', stack: 'CÔNG NGHỆ', experience: 'KINH NGHIỆM', projects: 'DỰ ÁN', contact: 'LIÊN HỆ ↗' },
    role: 'KỸ SƯ PHẦN MỀM',
    hello: 'XIN CHÀO, TÔI LÀ',
    headline: ['KỸ SƯ', 'PHẦN MỀM'],
    welcomeEyebrow: 'WElCOME TO',
    welcomeTitle: ['MY', 'PORTFOLIO.'],
    welcomeFooter: 'SCROLL TO EXPLORE ↓',
    viewProjects: 'XEM DỰ ÁN ↓',
    resume: 'TẢI CV ↗',
    summary:
      'Tôi học tốt nhất khi được tự tay làm: lần theo một câu hỏi đến tận gốc, thử đủ lâu để hiểu và chỉ giữ lại những điều thật sự hữu ích.',
    facts: [
      ['ĐÀO SÂU', 'CÁCH TÔI HỌC'],
      ['BỀN BỈ', 'CÁCH TÔI TIẾN BỘ'],
      ['HỒ CHÍ MINH', 'NƠI TÔI ĐANG SỐNG'],
    ],
    heroNotes: ['TÒ MÒ', 'KỸ LƯỠNG', 'HÒA ĐỒNG'],
    marquee: 'WEB DEVELOPMENT ✦ SYSTEM DESIGN ✦ REST API ✦ CLEAN ARCHITECTURE ✦',
    aboutIndex: '01 / VỀ TÔI',
    aboutTitle: ['TÔI LÀ AI.', 'CÁCH TÔI LÀM VIỆC.'],
    aboutText:
      'Tôi là người hòa đồng, vui vẻ và khá dễ bắt nhịp khi làm việc cùng mọi người. Nhưng với công việc, tôi luôn giữ sự nghiêm túc và trách nhiệm. Trước khi bắt tay vào một tính năng, tôi muốn có đủ bối cảnh: ai sẽ dùng, họ đang vướng ở đâu, quy trình hiện tại diễn ra thế nào và những trường hợp nào dễ bị bỏ sót. Khi mọi thứ đã rõ, tôi làm từng phần cẩn thận, kiểm tra kỹ và trao đổi lại ngay nếu vẫn còn điểm chưa chắc chắn. Với tôi, làm nhanh chỉ có ý nghĩa khi vẫn hiểu đúng và làm đến nơi đến chốn.',
    aboutMeta: [
      ['NGÀY SINH', '17/08/2003'],
      ['ĐANG SỐNG TẠI', 'TP. HỒ CHÍ MINH, VIỆT NAM'],
    ],
    principles: [
      ['01', 'HÒA ĐỒNG VÀ CỞI MỞ'],
      ['02', 'ĐỦ BỐI CẢNH RỒI MỚI LÀM'],
      ['03', 'NGHIÊM TÚC VÀ KỸ LƯỠNG'],
    ],
    stackIndex: '02 / CÔNG NGHỆ',
    stackTitle: 'CÔNG NGHỆ TÔI SỬ DỤNG.',
    stackNote: 'MỖI CÔNG NGHỆ Ở ĐÂY ĐỀU ĐÃ ĐƯỢC TÔI DÙNG ĐỂ GIẢI QUYẾT MỘT BÀI TOÁN THẬT.',
    stackGroups: [
      [
        'FRONTEND',
        ['ReactJS / Next.js', 'TypeScript / JavaScript', 'Tailwind CSS / shadcn/ui', 'TanStack Query / Zustand'],
      ],
      ['BACKEND', ['Python / Django / DRF', 'NestJS / ExpressJS', 'REST API', 'Authentication & Authorization']],
      ['DATABASE', ['PostgreSQL / MySQL', 'MongoDB', 'Query Optimization', 'Database Design']],
      [
        'TOOLS & PROCESS',
        ['Git / Docker / Linux', 'Unit & E2E Testing', 'System Integration', 'AI-assisted Development'],
      ],
    ],
    expIndex: '03 / KINH NGHIỆM',
    expTitle: ['NƠI TÔI', 'TẠO RA GIÁ TRỊ.'],
    expRole: 'KỸ SƯ PHẦN MỀM FULL-STACK',
    expCompany: 'TTMI JOINT STOCK COMPANY',
    expDate: '10/2025 — HIỆN TẠI',
    expStack: ['PYTHON', 'DJANGO', 'REACT', 'TYPESCRIPT', 'POSTGRESQL'],
    expDomainLabel: 'LĨNH VỰC',
    expDomains: ['F&B', 'E-COMMERCE', 'ERP'],
    expBullets: [
      'Xây dựng luồng e-commerce xuyên suốt cho đơn hàng, tồn kho, sản phẩm, giao vận, báo cáo và nhập/xuất Excel trên cả ứng dụng dành cho khách hàng lẫn hệ thống quản trị nội bộ.',
      'Phát triển các module POS và CRM cho dữ liệu menu đa thương hiệu, danh mục, tuỳ chọn sản phẩm, cấu hình cửa hàng và đồng bộ sản phẩm giữa các hệ thống.',
      'Triển khai nghiệp vụ ERP kho: tra cứu sản phẩm bằng barcode, theo dõi vị trí kệ, yêu cầu mua hàng, nhận hàng, thuế theo từng dòng và tự động tạo đơn mua hàng.',
      'Xây dựng giải pháp dữ liệu marketing gồm đồng bộ Facebook Insights theo lịch, caching, thu thập dữ liệu sản phẩm đối thủ và xử lý OCR Shopee với Gemini.',
      'Cải thiện API sản phẩm, đơn hàng, báo cáo và tồn kho bằng cách loại bỏ truy cập N+1, áp dụng eager loading, batch database operations và thêm regression test cho truy vấn.',
      'Làm việc trực tiếp với Accounting, Sales, Marketing và Ban Giám đốc để làm rõ yêu cầu, chuyển hoá quy trình kinh doanh thành các tính năng đã được kiểm thử.',
    ],
    education: 'HỌC VẤN',
    degree: 'KỸ SƯ CÔNG NGHỆ THÔNG TIN · GPA 3.0/4.0',
    school: 'ĐẠI HỌC NAM CẦN THƠ · 2021—2025',
    projectsIndex: '04 / DỰ ÁN TIÊU BIỂU',
    projectsTitle: 'NHỮNG THỨ TÔI TỰ TAY XÂY DỰNG.',
    projectsNote: 'ĐÂY LÀ NƠI TÔI HỌC BẰNG CÁCH LÀM, SAI, SỬA VÀ CUỐI CÙNG BIẾN Ý TƯỞNG THÀNH THỨ CÓ THỂ CHẠY.',
    projects: [
      {
        title: 'CRM & E-COMMERCE LINH KIỆN ĐIỆN TỬ',
        label: 'DỰ ÁN TỰ XÂY DỰNG · FULL-STACK',
        visual: 'CRM',
        badge: 'FULL STACK',
        description:
          'Tôi bắt đầu dự án này vì muốn tự mình đi hết một vòng của một sản phẩm bán hàng: từ lúc khách chọn linh kiện cho đến những việc phía sau như quản lý tồn kho, xử lý đơn và theo dõi doanh thu. Quá trình đó giúp tôi hiểu rõ hơn cách chia trách nhiệm ở backend, đồng thời giữ cho giao diện, API và dữ liệu không lệch khỏi nhau.',
        features: [
          'Khách hàng có thể tạo tài khoản, tìm sản phẩm, quản lý giỏ hàng, thanh toán COD hoặc PayPal và xem lại lịch sử mua hàng.',
          'Phía quản trị có phân quyền riêng để quản lý sản phẩm, danh mục, hình ảnh, khách hàng, nhân viên và trạng thái đơn hàng.',
          'Luồng kho hỗ trợ nhập, xuất và theo dõi lượng tồn; khách hàng nhận được email xác nhận ngay khi đơn được tạo.',
          'Dashboard tổng hợp doanh thu theo ngày, tháng và năm để người vận hành nắm nhanh tình hình bán hàng.',
          'Backend được tách theo Route → Controller → Service → Repository, dùng Zod để kiểm tra dữ liệu, Firebase để lưu hình ảnh và Docker khi triển khai.',
        ],
        tech: 'REACT · TYPESCRIPT · REDUX TOOLKIT · ANT DESIGN · EXPRESS · PRISMA · MYSQL · DOCKER',
        links: [
          ['BACKEND REPOSITORY ↗', 'https://github.com/Trqkhanh17/Backend_LinhKienDienTu'],
          ['FRONTEND REPOSITORY ↗', 'https://github.com/Trqkhanh17/FrontEnd_BanLinhKienDienTu'],
        ],
      },
      {
        title: 'COFFEE STYLE — RESPONSIVE E-COMMERCE UI',
        label: 'DỰ ÁN TỰ XÂY DỰNG · GIAO DIỆN',
        visual: 'UI',
        badge: 'GIAO DIỆN',
        description:
          'Dự án này bắt đầu như một bài tập về khoảng cách, nhịp nội dung và cách giao diện thích nghi trên từng màn hình. Tôi không muốn dừng ở một trang chủ trông đẹp mắt, nên đã làm trọn hành trình từ xem sản phẩm, tìm hiểu câu chuyện thương hiệu đến thao tác với giỏ hàng.',
        features: [
          'Trang chủ dẫn dắt câu chuyện thương hiệu bằng banner chuyển động, sản phẩm nổi bật, chuyên mục cà phê, nội dung phong cách sống và bản tin email.',
          'Danh mục có bộ lọc; trang chi tiết đặt mô tả, điểm nổi bật và sản phẩm liên quan trong cùng một mạch xem liền lạc.',
          'Giỏ hàng mở bằng một khung trượt, hỗ trợ thêm, xóa, gộp số lượng, tính tạm tính và cả trạng thái chưa có sản phẩm.',
          'Các trang Giới thiệu, Blog, Liên hệ, bản đồ, biểu mẫu và trang 404 đều giữ chung một ngôn ngữ thiết kế.',
          'Các trang chỉ được tải khi cần, chuyển động dùng Framer Motion và giao diện thích ứng từ điện thoại đến màn hình lớn.',
        ],
        tech: 'REACT 19 · TYPESCRIPT · TAILWIND CSS · FRAMER MOTION · REACT ROUTER · VITE',
        links: [['REPOSITORY ↗', 'https://github.com/Trqkhanh17/TailwindCSS-Coffee-Style']],
      },
      {
        title: 'AI TRAVEL & OUTING PLANNER SERVER',
        label: 'DỰ ÁN TỰ XÂY DỰNG · BACKEND & AI',
        visual: 'AI',
        badge: 'AI BACKEND',
        description:
          'Tôi xây dựng backend cho ứng dụng lập kế hoạch du lịch và đi chơi tự động bằng AI, giải quyết việc tốn nhiều thời gian lên lịch trình, tìm kiếm địa điểm và cân đối ngân sách. Hệ thống tích hợp trực tiếp Google Gemini AI với kỹ thuật Structured Outputs (JSON Schema) để tạo lịch trình chi tiết và nhất quán, đồng thời quản lý quota gọi AI hàng ngày theo người dùng và địa chỉ IP.',
        features: [
          'Tự động phân tích ngân sách, số lượng người, điểm khởi hành và sở thích để tạo lịch trình chi tiết theo buổi (sáng, chiều, tối), kèm gợi ý ăn uống, tham quan và ước tính chi phí.',
          'Ứng dụng kỹ thuật Structured Outputs (JSON Schema) khi gọi Google Gemini AI (@google/genai) để đảm bảo 100% dữ liệu trả về đúng định dạng, loại bỏ hoàn toàn rủi ro sai lệch cấu trúc JSON.',
          'Lưu trữ và quản lý lịch trình trên MongoDB, hỗ trợ phân trang lịch sử, gán lịch trình tạo ẩn danh vào tài khoản đăng ký (claim guest trip) và bật/tắt chia sẻ công khai.',
          'Kiểm soát chi phí & tài nguyên: giới hạn quota gọi AI hàng ngày cho người dùng và khách vãng lai thông qua định danh mã hóa HMAC-SHA256, kết hợp rate limiting với @nestjs/throttler.',
          'Hệ thống xác thực và bảo mật hoàn chỉnh: JWT Access & Refresh Token (hỗ trợ thu hồi phiên), xác minh tài khoản qua email và đổi mật khẩu bằng mã OTP với Nodemailer / Resend API.',
        ],
        tech: 'NESTJS 11 · TYPESCRIPT · MONGODB · MONGOOSE 8 · GOOGLE GEMINI AI · PASSPORT · JWT · NODEMAILER · DOCKER',
        links: [['REPOSITORY ↗', 'https://github.com/Trqkhanh17/ai-travel-planner-server']],
      },
    ],
    contactIndex: '05 / LIÊN HỆ',
    contactLead:
      'NẾU BẠN CẦN MỘT KỸ SƯ PHẦN MỀM LUÔN MUỐN HIỂU RÕ VIỆC CẦN LÀM, KHÔNG NGẠI HỌC ĐIỀU MỚI VÀ SẴN SÀNG CÙNG ĐỘI NGŨ TÌM RA CÁCH TỐT HƠN,',
    contactTitle: ['CỨ NHẮN CHO TÔI.', 'TÔI SẴN SÀNG LẮNG NGHE.'],
    email: 'EMAIL',
    github: 'GITHUB',
    phone: 'ĐIỆN THOẠI',
    footer: 'PORTFOLIO KỸ SƯ PHẦN MỀM',
    top: 'VỀ ĐẦU TRANG ↑',
  },
  en: {
    nav: { about: 'ABOUT', stack: 'SKILLS', experience: 'EXPERIENCE', projects: 'PROJECTS', contact: 'CONTACT ↗' },
    role: 'SOFTWARE ENGINEER',
    hello: "HELLO, I'M",
    headline: ['SOFTWARE', 'ENGINEER'],
    welcomeEyebrow: 'WELCOME TO',
    welcomeTitle: ['MY', 'PORTFOLIO.'],
    welcomeFooter: 'SCROLL TO EXPLORE ↓',
    viewProjects: 'VIEW PROJECTS ↓',
    resume: 'DOWNLOAD CV ↗',
    summary:
      'I like to learn slowly but thoroughly: follow an idea far enough to understand it, try it for myself, and keep what proves genuinely useful.',
    facts: [
      ['CURIOUS', 'BY NATURE'],
      ['CONSISTENT', 'HOW I GROW'],
      ['HO CHI MINH', 'BASED IN'],
    ],
    heroNotes: ['CURIOUS BY NATURE', 'SERIOUS ABOUT DETAILS', 'EASY TO WORK WITH'],
    marquee: 'WEB DEVELOPMENT ✦ SYSTEM DESIGN ✦ REST API ✦ CLEAN ARCHITECTURE ✦',
    aboutIndex: '01 / ABOUT',
    aboutTitle: ['WHO I AM.', 'HOW I WORK.'],
    aboutText:
      "I'm easygoing, upbeat, and quick to connect with the people I work with, but I take the work itself seriously. Before I start building a feature, I want the full context: who will use it, where the current friction is, how the workflow runs, and which cases are easy to miss. Once that picture is clear, I work carefully, check the details, and raise questions whenever something still feels uncertain. To me, moving fast only matters when the work is still understood and done properly.",
    aboutMeta: [
      ['DATE OF BIRTH', '17 AUGUST 2003'],
      ['BASED IN', 'HO CHI MINH CITY, VIETNAM'],
    ],
    principles: [
      ['01', 'OPEN AND EASY TO WORK WITH'],
      ['02', 'GET THE FULL CONTEXT FIRST'],
      ['03', 'SERIOUS ABOUT THE DETAILS'],
    ],
    stackIndex: '02 / SKILLS',
    stackTitle: 'TOOLS I USE.',
    stackNote: 'THE TECHNOLOGIES I USE AT WORK AND IN THE PROJECTS I BUILD FOR MYSELF.',
    stackGroups: [
      [
        'FRONTEND',
        ['ReactJS / Next.js', 'TypeScript / JavaScript', 'Tailwind CSS / shadcn/ui', 'TanStack Query / Zustand'],
      ],
      ['BACKEND', ['Python / Django / DRF', 'NestJS / ExpressJS', 'REST API', 'Authentication & Authorization']],
      ['DATABASE', ['PostgreSQL / MySQL', 'MongoDB', 'Query Optimization', 'Database Design']],
      ['ENGINEERING', ['Git / Docker / Linux', 'Unit & E2E Testing', 'System Integration', 'AI-assisted Development']],
    ],
    expIndex: '03 / EXPERIENCE',
    expTitle: ['WHERE I', 'CREATE VALUE.'],
    expRole: 'FULL-STACK SOFTWARE ENGINEER',
    expCompany: 'TTMI JOINT STOCK COMPANY',
    expDate: 'OCT 2025 — PRESENT',
    expStack: ['PYTHON', 'DJANGO', 'REACT', 'TYPESCRIPT', 'POSTGRESQL'],
    expDomainLabel: 'DOMAINS',
    expDomains: ['F&B', 'E-COMMERCE', 'ERP'],
    expBullets: [
      'Develop full-stack e-commerce workflows for orders, inventory, products, delivery, reporting, and Excel import/export across customer-facing and internal administration applications.',
      'Build POS and CRM modules for multi-brand menu data, item categories, customizations, store configuration, and cross-system product synchronization.',
      'Implement ERP warehouse workflows for barcode product lookup, shelf-location tracking, purchase requests, goods receiving, line-level tax, and automated purchase-order creation.',
      'Deliver marketing data solutions including scheduled Facebook Insights synchronization, caching, competitor-product scraping, and Gemini-powered Shopee OCR processing.',
      'Improve product, order, reporting, and stock APIs by eliminating N+1 access patterns, adding eager loading, batching database operations, and introducing regression tests for query behavior.',
      'Work directly with Accounting, Sales, Marketing, and the Board of Directors to clarify requirements and translate business workflows into tested product features.',
    ],
    education: 'EDUCATION',
    degree: 'B.ENG. IN INFORMATION TECHNOLOGY · GPA 3.0/4.0',
    school: 'NAM CAN THO UNIVERSITY · 2021—2025',
    projectsIndex: '04 / SELECTED BUILDS',
    projectsTitle: 'THINGS I BUILD.',
    projectsNote: 'PERSONAL PROJECTS THAT HELP ME LEARN HOW AN IDEA BECOMES WORKING SOFTWARE.',
    projects: [
      {
        title: 'ELECTRONICS CRM & E-COMMERCE',
        label: 'PERSONAL PROJECT · FULL-STACK',
        visual: 'CRM',
        badge: 'FULL STACK',
        description:
          "I built this project to follow an online-sale product from end to end: the customer's search for the right component and the less visible work behind it — stock, orders, customers, and revenue. It also became a place to practice separating backend responsibilities while keeping the interface, API, and data model in step.",
        features: [
          'Customers can create an account, find components, manage a cart, check out with COD or PayPal, and revisit previous orders.',
          'The admin side has separate permissions for products, categories, images, customers, staff, and order status.',
          'Inventory flows cover stock in, stock out, and current quantities; a confirmation email follows each new order.',
          'The dashboard groups revenue by day, month, and year so the operator can get a quick view of sales.',
          'The backend follows Route → Controller → Service → Repository, with Zod validation, Firebase uploads, and Docker for deployment.',
        ],
        tech: 'REACT · TYPESCRIPT · REDUX TOOLKIT · ANT DESIGN · EXPRESS · PRISMA · MYSQL · DOCKER',
        links: [
          ['BACKEND REPOSITORY ↗', 'https://github.com/Trqkhanh17/Backend_LinhKienDienTu'],
          ['FRONTEND REPOSITORY ↗', 'https://github.com/Trqkhanh17/FrontEnd_BanLinhKienDienTu'],
        ],
      },
      {
        title: 'COFFEE STYLE — RESPONSIVE E-COMMERCE UI',
        label: 'PERSONAL PROJECT · UI',
        visual: 'UI',
        badge: 'UI DESIGN',
        description:
          'I built this UI project to sharpen my sense of spacing, content rhythm, and how a design should respond at different screen sizes. Instead of stopping at an attractive homepage, I completed the wider journey through products, brand stories, and the shopping cart.',
        features: [
          'The homepage tells the brand story through a hero slider, featured products, coffee magazine, lifestyle stories, and a newsletter.',
          'The catalog is filterable, while each product page brings its story, highlights, and related suggestions into one natural flow.',
          'The cart opens as a drawer and handles adding, removing, merged quantities, subtotal calculation, and an empty state.',
          'About, Blog, Contact, map, form, and 404 pages all follow the same visual language.',
          'Routes are lazy-loaded, motion comes from Framer Motion, and the layout adapts from mobile through desktop.',
        ],
        tech: 'REACT 19 · TYPESCRIPT · TAILWIND CSS · FRAMER MOTION · REACT ROUTER · VITE',
        links: [['REPOSITORY ↗', 'https://github.com/Trqkhanh17/TailwindCSS-Coffee-Style']],
      },
      {
        title: 'AI TRAVEL & OUTING PLANNER SERVER',
        label: 'PERSONAL PROJECT · BACKEND & AI',
        visual: 'AI',
        badge: 'AI BACKEND',
        description:
          'I built the backend server for an AI-powered travel and outing planning platform to eliminate the friction of manual itinerary research, place discovery, and budget allocation. The system integrates Google Gemini AI with strict Structured Outputs (JSON Schema) for consistent, predictable itineraries, protected by daily per-user and per-guest IP quota management.',
        features: [
          'Automated AI itinerary generation: analyzes budget, origin, group size, and preferences to output morning/afternoon/evening schedules, curated dining spots, attractions, and cost breakdowns.',
          '100% schema-consistent AI responses using Google Gemini AI (@google/genai) with JSON Schema to ensure fully structured, predictable output without formatting errors.',
          'MongoDB persistence for trip plans, supporting history pagination, guest plan claiming into registered accounts, and public/private sharing toggle.',
          'Quota protection & rate limiting: enforces daily AI generation limits per user and per guest IP tracked via HMAC-SHA256 hashing, backed by @nestjs/throttler.',
          'Full auth & mailing flow: JWT access & refresh tokens with session revocation, email verification, and OTP password recovery via Nodemailer / Resend API.',
        ],
        tech: 'NESTJS 11 · TYPESCRIPT · MONGODB · MONGOOSE 8 · GOOGLE GEMINI AI · PASSPORT · JWT · NODEMAILER · DOCKER',
        links: [['REPOSITORY ↗', 'https://github.com/Trqkhanh17/ai-travel-planner-server']],
      },
    ],
    contactIndex: '05 / CONTACT',
    contactLead:
      'IF YOU NEED A SOFTWARE ENGINEER WHO LIKES TO UNDERSTAND THE WORK BEFORE WRITING THE CODE — AND KEEPS LEARNING ALONG THE WAY,',
    contactTitle: ["LET'S TALK.", "I'M LISTENING."],
    email: 'EMAIL',
    github: 'GITHUB',
    phone: 'PHONE',
    footer: 'SOFTWARE ENGINEER PORTFOLIO',
    top: 'BACK TO TOP ↑',
  },
} as const;
